### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by mpostol** [nathanpocock/I-ISMS#1]
I am not expert by the statement:
```
These documents are not for sale. Using them or creating documents based on them cannot be sold without express permission from the author.
`````
is inconsistent with the MIT license at [Information Management Security System Document Template Library](https://nathanpocock.github.io/I-ISMS/)

Add the link to license document in the README.md

**Comment by nathanpocock** [comment]
Agreed. I just wanted to be clear to all that these documents cannot be sold. 
I've removed the text.

**Comment by mpostol** [comment]
Hopefully intellectual properties without author are usually useless.
